repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=500]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.1
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
- repo: https://github.com/omnilib/ufmt
  rev: v2.0.0rc1
  hooks:
  - id: ufmt
    additional_dependencies:
    - black == 22.6.0
    - usort == 1.0.4
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    additional_dependencies: [types-all]
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint
    args: [--disable=import-error]
